# 04 — Desbalanceamento e limiar

## Objetivo

O desbalanceamento deve ser tratado com pesos, com SMOTENC ou com a escolha
do limiar?

Partimos do Gradient Boosting otimizado na Aula 3. Pesos e SMOTENC alteram
somente o treino; a validação permanece intacta e o teste continua fechado.

In [3]:
from pathlib import Path
import sys

ponto_atual = Path.cwd().resolve()
RAIZ = next(
    caminho for caminho in (ponto_atual, *ponto_atual.parents)
    if (caminho / "data" / "raw" / "UCI_Credit_Card.csv").exists()
)
if str(RAIZ) not in sys.path:
    sys.path.insert(0, str(RAIZ))


import json
import time
import numpy as np
import pandas as pd
from imblearn.over_sampling import SMOTENC
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import (
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_recall_curve,
    precision_score,
    recall_score,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.utils.class_weight import compute_sample_weight

from src.auxiliares import (
    COLUNAS_NOMINAIS,
    COLUNAS_STATUS,
)
from src.visual_utils import (
    grafico_curvas_precision_recall,
    grafico_metricas_por_limiar,
)

pasta_processados = RAIZ / "data" / "processed"
dados_treino = pd.read_csv(pasta_processados / "treino.csv")
dados_validacao = pd.read_csv(pasta_processados / "validacao.csv")

X_treino = dados_treino.drop(columns=["inadimplente"])
y_treino = dados_treino["inadimplente"]

X_validacao = dados_validacao.drop(columns=["inadimplente"])
y_validacao = dados_validacao["inadimplente"]

caminho_parametros = RAIZ / "models" / "parametros_gradient_boosting.json"
if not caminho_parametros.exists():
    raise FileNotFoundError(
        "Execute primeiro o notebook 03_otimizacao.ipynb."
    )

parametros = json.loads(caminho_parametros.read_text(encoding="utf-8"))

## 4.1 — Como se comporta o modelo original?

Reconstruímos o Gradient Boosting com os parâmetros salvos na Aula 3 e os
dados de treino originais.

In [5]:
# Mesmo pré-processamento da Aula 2: one-hot nas nominais e demais colunas sem alteração.
preprocessamento_arvores = ColumnTransformer(
    [(
        "nominais",
        OneHotEncoder(handle_unknown="ignore", sparse_output=False),
        COLUNAS_NOMINAIS,
    )],
    remainder="passthrough",
    verbose_feature_names_out=False,
)

In [4]:
## GB Otimizado

modelo_otimizado = Pipeline([
    (
        'preprocessamento',
        preprocessamento_arvores,
    ),
    (
        'modelo',
        GradientBoostingClassifier(**parametros,
                                  random_state=42,
                               )
    ),
])

## Tempo + Treinamento

inicio = time.perf_counter()

modelo_otimizado.fit(
    X_treino,
    y_treino,
)

tempo_otimizado = (time.perf_counter() - inicio)

## Classe e Probabilidade
previsoes_otimizadas = modelo_otimizado.predict(X_validacao)


probabilidades_otimizadas = modelo_otimizado.predict_proba(X_validacao)[:,1]

## Average Precision
ap_gb_otimizado = average_precision_score(
    y_validacao,
    probabilidades_otimizadas
    
)

## 4.2 — Pesos aumentam o alcance da classe positiva?

Com pesos balanceados, cada inadimplente pesa mais no treino. Os pesos entram
somente no `fit`.

In [6]:
pesos = compute_sample_weight(
    class_weight="balanced",
    y=y_treino
)

print(pd.DataFrame(
    {
    "Classe": y_treino,
    "Peso": pesos
    }
).groupby("Classe")["Peso"].mean().round(3)
      )

Classe
0    0.642
1    2.260
Name: Peso, dtype: float64

In [7]:
## GB Otimizado

modelo_pesos = Pipeline([
    (
        'preprocessamento',
        preprocessamento_arvores,
    ),
    (
        'modelo',
        GradientBoostingClassifier(**parametros,
                                  random_state=42,
                               )
    ),
])

## Tempo + Treinamento

inicio = time.perf_counter()

modelo_pesos.fit(
    X_treino,
    y_treino,
    modelo__sample_weight = pesos
)

tempo_pesos = (time.perf_counter() - inicio)

## Classe e Probabilidade
previsoes_pesos = modelo_pesos.predict(X_validacao)


probabilidades_pesos = modelo_pesos.predict_proba(X_validacao)[:,1]

## Average Precision
ap_pesos= average_precision_score(
    y_validacao,
    probabilidades_pesos
    
)

In [11]:
matriz_otimizada = confusion_matrix(
    y_validacao, 
    previsoes_otimizadas, 
    labels=[0,1]
)

matriz_pesos = confusion_matrix(
    y_validacao, 
    previsoes_pesos, 
    labels=[0,1]
)

comparacao_pesos = pd.DataFrame([

    {
        "Estratégia": "Dados Originais",
        "Precision": precision_score(y_validacao,previsoes_otimizadas),
        "Recall": recall_score(y_validacao,previsoes_otimizadas),
        "f1": f1_score(y_validacao,previsoes_otimizadas),
        "AP": ap_gb_otimizado,
        "FP": matriz_otimizada[0,1],
        "FN": matriz_otimizada[1,0],
    },
    {
        "Estratégia": "Dados com Pesos",
        "Precision": precision_score(y_validacao,previsoes_pesos),
        "Recall": recall_score(y_validacao,previsoes_pesos),
        "f1": f1_score(y_validacao,previsoes_pesos),
        "AP": ap_pesos,
        "FP": matriz_pesos[0,1],
        "FN": matriz_pesos[1,0],
    },
   
   
])

comparacao_pesos.round(3)

        Estratégia  Precision  Recall     f1     AP   FP   FN
0  Dados Originais      0.678   0.362  0.472  0.551  228  847
1  Dados com Pesos      0.474   0.616  0.536  0.550  906  509

## 4.3 — O SMOTENC melhora o ranking?

Sexo, escolaridade, estado civil e os status de pagamento (-2 a 8) são códigos
discretos: um status 1,4 não existe. Por isso, `COLUNAS_NOMINAIS +
COLUNAS_STATUS` entram como categóricas no SMOTENC, aplicado apenas ao treino.

In [18]:
colunas_categoricas = COLUNAS_NOMINAIS + COLUNAS_STATUS
  
indices_categoricas = [
    X_treino.columns.get_loc(coluna)
    for coluna in colunas_categoricas
] 

smotenc = SMOTENC(
    categorical_features=indices_categoricas,
    random_state=42
) 
 
print("Antes do SMOTENC:")
print(y_treino.value_counts())


X_treino_smotenc, y_treino_smotenc = smotenc.fit_resample(
    X_treino,
    y_treino
) 

print("Depois do SMOTENC:")
print(y_treino_smotenc.value_counts())


## GB Com smote

modelo_smotenc = Pipeline([
    (
        'preprocessamento',
        preprocessamento_arvores,
    ),
    (
        'modelo',
        GradientBoostingClassifier(**parametros,
                                  random_state=42,
                               )
    ),
])

## Tempo + Treinamento

inicio = time.perf_counter()

modelo_smotenc.fit(
    X_treino_smotenc,
    y_treino_smotenc
)

tempo_smotenc = (time.perf_counter() - inicio)

## Classe e Probabilidade
previsoes_smotenc = modelo_smotenc.predict(X_validacao)


probabilidades_smotenc = modelo_smotenc.predict_proba(X_validacao)[:,1]

## Average Precision
ap_smotenc= average_precision_score(
    y_validacao,
    probabilidades_smotenc
    
)
   
print(f"Average Precision: {ap_smotenc:.3f}")



matriz_smotenc = confusion_matrix(
    y_validacao, 
    previsoes_smotenc, 
    labels=[0,1]
)

comparacao_pesos = pd.DataFrame([

    {
        "Estratégia": "Dados Originais",
        "Precision": precision_score(y_validacao,previsoes_otimizadas),
        "Recall": recall_score(y_validacao,previsoes_otimizadas),
        "f1": f1_score(y_validacao,previsoes_otimizadas),
        "AP": ap_gb_otimizado,
        "FP": matriz_otimizada[0,1],
        "FN": matriz_otimizada[1,0],
    },
    {
        "Estratégia": "Dados com Pesos",
        "Precision": precision_score(y_validacao,previsoes_pesos),
        "Recall": recall_score(y_validacao,previsoes_pesos),
        "f1": f1_score(y_validacao,previsoes_pesos),
        "AP": ap_pesos,
        "FP": matriz_pesos[0,1],
        "FN": matriz_pesos[1,0],
    },
    {
        "Estratégia": "SMOTENC",
        "Precision": precision_score(y_validacao,previsoes_smotenc),
        "Recall": recall_score(y_validacao,previsoes_smotenc),
        "f1": f1_score(y_validacao,previsoes_smotenc),
        "AP": ap_smotenc,
        "FP": matriz_smotenc[0,1],
        "FN": matriz_smotenc[1,0],
    },
   
   
])

comparacao_pesos.round(3)

Antes do SMOTENC:
inadimplente
0    14018
1     3982
Name: count, dtype: int64
Depois do SMOTENC:
inadimplente
0    14018
1    14018
Name: count, dtype: int64
Average Precision: 0.525

        Estratégia  Precision  Recall     f1     AP   FP   FN
0  Dados Originais      0.678   0.362  0.472  0.551  228  847
1  Dados com Pesos      0.474   0.616  0.536  0.550  906  509
2          SMOTENC      0.490   0.547  0.517  0.525  756  601

## 4.4 — Qual estratégia preserva melhor a Average Precision (AP)?

Precision, Recall, F1 e falsos positivos (FP) usam o limiar de 0,50. A AP
resume o ranking ao longo de todos os limiares.

In [17]:
precision_original, recall_original, _ = precision_recall_curve(
    y_validacao,
    probabilidades_otimizadas
)

precision_com_pesos, recall_com_pesos, _ = precision_recall_curve(
    y_validacao,
    probabilidades_pesos
)

precision_smotenc, recall_smotenc, _ = precision_recall_curve(
    y_validacao,
    probabilidades_smotenc
)

In [19]:
colunas_comparacao = [
    "Estratégia",
    "AP",
    "Precision",
    "Recall",
    "f1",
    "FP",
    "FN",
]

comparacao_pesos[
    colunas_comparacao
].sort_values("AP", ascending=False).round(3)

        Estratégia     AP  Precision  Recall     f1   FP   FN
0  Dados Originais  0.551      0.678   0.362  0.472  228  847
1  Dados com Pesos  0.550      0.474   0.616  0.536  906  509
2          SMOTENC  0.525      0.490   0.547  0.517  756  601

In [21]:
ap_por_estrategia = comparacao_pesos.set_index("Estratégia")["AP"]

fig = grafico_curvas_precision_recall(
    {
        f"Dados Originais (AP = {ap_por_estrategia['Dados Originais']:.3f})": (recall_original, precision_original),
        f"Dados com Pesos (AP = {ap_por_estrategia['Dados com Pesos']:.3f})": (recall_com_pesos, precision_com_pesos),
        f"SMOTENC (AP = {ap_por_estrategia['SMOTENC']:.3f})": (recall_smotenc, precision_smotenc),
    },
    titulo="Curva Precision-Recall por estratégia de treino",
    taxa_positiva=y_validacao.mean(),
)
fig.show()

Os pesos elevam o Recall no limiar 0,50, mas multiplicam os falsos positivos e
deixam a AP praticamente igual: as curvas de dados originais e pesos quase se
sobrepõem. O ranking não melhora; a régua de decisão apenas se desloca. O
SMOTENC reduz a AP e acrescenta uma etapa ao treino. Seguimos com os dados
originais e tratamos o desbalanceamento na escolha do limiar.

## 4.5 — O que muda quando alteramos o limiar?

Probabilidade não é classe. Um limiar menor classifica mais clientes como
inadimplentes: o Recall tende a subir e a Precision tende a cair.

In [26]:
limiares = [0.50, 0.40, 0.31, 0.30, 0.27, 0.24]
registros = []

for limiar in limiares:
    previsoes = (probabilidades_otimizadas >= limiar).astype(int)
    matriz = confusion_matrix(y_validacao,
                              previsoes,
                              labels=[0,1])
    registros.append({        
        "limiar": limiar,
        "precision": precision_score(y_validacao,previsoes),
        "recall": recall_score(y_validacao,previsoes),
        "f1": f1_score(y_validacao,previsoes),
        "FP": matriz[0,1],
        "FN": matriz[1,0],
    })
    
resultados_limiares = pd.DataFrame(registros)
resultados_limiares.round(3)

   limiar  precision  recall     f1   FP   FN
0    0.50      0.678   0.362  0.472  228  847
1    0.40      0.617   0.429  0.506  353  758
2    0.31      0.555   0.522  0.538  555  634
3    0.30      0.543   0.539  0.541  601  612
4    0.27      0.518   0.561  0.538  693  583
5    0.24      0.489   0.598  0.538  830  534

In [27]:
fig = grafico_metricas_por_limiar(resultados_limiares)
fig.show()

Entre 0,24 e 0,31, o F1 fica praticamente estável. Dentro dessa faixa,
escolhemos 0,27, que privilegia o Recall sem derrubar a Precision. É uma
decisão deste projeto, tomada na validação, e não um valor universal.

In [28]:
limiar_escolhido = 0.27

previsoes_limiar = (
    probabilidades_otimizadas >= limiar_escolhido
).astype(int)

resultados_limiares[resultados_limiares["limiar"]
                    .isin([0.50, limiar_escolhido])].round(3)

   limiar  precision  recall     f1   FP   FN
0    0.50      0.678   0.362  0.472  228  847
4    0.27      0.518   0.561  0.538  693  583

In [29]:
decisao_limiar = {
    "limiar": float(limiar_escolhido),
    "balanceamento": "dados originais",
    "escolhido_em": "validação",
}

caminho_limiar = RAIZ / "models" / "limiar_decisao.json"
caminho_limiar.parent.mkdir(parents=True, exist_ok=True)
caminho_limiar.write_text(
    json.dumps(decisao_limiar, ensure_ascii=False, indent=2),
    encoding="utf-8",
)
print(f"Decisão salva em: {caminho_limiar}")
decisao_limiar

Decisão salva em: C:\GitHub\ALURA\classificacao-avancando-classificadores\models\limiar_decisao.json

{'limiar': 0.27,
 'balanceamento': 'dados originais',
 'escolhido_em': 'validação'}

## 4.6 — Resultado

Pesos não melhoram o ranking de forma relevante e o SMOTENC piora a AP; os
dados originais permanecem. O desbalanceamento passa a ser tratado na
decisão: com limiar 0,27, o Recall de validação sobe de 0,36 para 0,56, ao
custo de mais falsos positivos. O limiar fica salvo e congelado antes de
abrir o teste.